import NavbarComponent from "@/components/NavbarComponent";
import SidebarComponent from "@/components/SidebarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex gap-10 h-screen">
      <SidebarComponent />
      <div className="w-full">
        <NavbarComponent />
        {children}
      </div>
    </div>
  );
}
